# Generated by Django 5.2.7 on 2025-11-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_house_alter_student_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='randomization_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='randomized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
