# Generated by Django 5.2.7 on 2025-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_department_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
