# Generated by Django 5.2.7 on 2025-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_student_registered_date_alter_student_matric_number'),
        ('houses', '0004_house_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['matric_number'], name='core_studen_matric__dcc9af_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['house'], name='core_studen_house_i_2428a7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['randomization_complete'], name='core_studen_randomi_0b77b9_idx'),
        ),
    ]
