# Generated by Django 5.2.7 on 2025-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('motto', models.TextField()),
                ('crest', models.ImageField(upload_to='house_crests/')),
                ('color_primary', models.CharField(default='#2B0000', max_length=7)),
                ('color_secondary', models.CharField(default='#0C0000', max_length=7)),
                ('whatsapp_link', models.URLField(blank=True)),
            ],
        ),
    ]
