# Generated by Django 5.2.7 on 2025-10-11 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='color_primary',
        ),
        migrations.RemoveField(
            model_name='house',
            name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='house',
            name='crest',
        ),
        migrations.RemoveField(
            model_name='house',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='house',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='houses/logos/'),
        ),
        migrations.AddField(
            model_name='house',
            name='primary_color',
            field=models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #1a2b3c', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='house',
            name='secondary_color',
            field=models.CharField(default='#6b7280', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #1a2b3c', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='motto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
