# Generated by Django 5.2.7 on 2025-10-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_remove_house_color_primary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='primary_color',
            new_name='color_primary',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='secondary_color',
            new_name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='house',
            name='logo',
        ),
        migrations.AddField(
            model_name='house',
            name='crest',
            field=models.ImageField(blank=True, null=True, upload_to='house_crests/'),
        ),
    ]
