# Generated by Django 5.2.7 on 2025-10-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_rename_primary_color_house_color_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
